### ISSUE TITLE
Plugins from repos besides central

### ISSUE THREAD

**Issue by adjohnson916** [gleclaire/findbugs-maven-plugin#14]
I wasn't able to configure this plugin with its nested `plugins` option to use any repository in my POM or `settings.xml` - it seems to always assume Maven central.

**Comment by gleclaire** [comment]
Do you have a sample?  We use this with regularly with plugins in private repos along with central

**Comment by adjohnson916** [comment]
There must have been something wrong with my Maven configuration - repositories or proxy configuration. I'm able to get it to work now. Thanks, and sorry to raise alarm.

**Comment by gleclaire** [comment]
no problem, happens to us all ;)
