### ISSUE TITLE
Missing test classes when includeTests is set

### ISSUE THREAD

**Issue by ctubbsii** [gleclaire/findbugs-maven-plugin#15]
JUnit and other tests are still missing from the classpath when the plugin runs. This was reported marked as fixed in https://jira.codehaus.org/browse/MFINDBUGS-201, but is still valid against 3.0.0 and 3.0.1.

**Comment by jsotuyod** [comment]
+1 seeing the same here

**Comment by mkordas** [comment]
+1

**Comment by ctubbsii** [comment]
Awesome. Thanks for the fix (will test when I get a chance). What's the anticipated milestone for this? 3.0.2?

**Comment by gleclaire** [comment]
yes
