### ISSUE TITLE
Documentation for thresholds

### ISSUE THREAD

**Issue by adjohnson916** [gleclaire/findbugs-maven-plugin#17]
Is there any documentation for the various threshold settings?

**Comment by gleclaire** [comment]
http://findbugs.sourceforge.net/manual/index.html

**Comment by ckarthik17** [comment]
is this the one you are referring?

reportLevel
An optional attribute. It specifies the confidence/priority threshold for reporting issues. If set to "low", confidence is not used to filter bugs. If set to "medium" (the default), low confidence issues are supressed. If set to "high", only high confidence bugs are reported.

**Comment by adjohnson916** [comment]
@ckarthik17 Yes, I'm referring to `reportLevel`, but this project calls it `threshold` which is not obvious, and if I recall correctly, does not accept lowercase, e.g. `low`, but only proper case, e.g. `Low`, unlike FindBugs.

Also, there appear to be no examples in the [usage] docs that demonstrate using it.
Hence the request to document it.

[usage]: https://gleclaire.github.io/findbugs-maven-plugin/usage.html
