### ISSUE TITLE
FindBugs 3.0.1 maven plugin doesn't work with Java 8

### ISSUE THREAD

**Issue by annbest** [gleclaire/findbugs-maven-plugin#19]
Hi,

When I tried to upgrade to Java 8 and findbugs 3.0.1 maven plugin, findbugs report is not generated using maven clean site.  I have findbugs maven plugin added in the reporting section and not under build section in pom.xml. It does seem to generate report when I add the plugin element in build section. 

Appreciate your help,
Thanks
A

**Comment by gleclaire** [comment]
Do you have a sample project to show the error?

**Comment by annbest** [comment]
Thanks for your response.

Here's the pom.xml: 
<reporting>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-project-info-reports-plugin</artifactId>
			<version>2.7</version>
			<configuration>
				<dependencyLocationsEnabled>false</dependencyLocationsEnabled>
			</configuration>
		</plugin>
		<plugin>
			<groupId>org.codehaus.mojo</groupId>
			<artifactId>findbugs-maven-plugin</artifactId>
			<version>3.0.1</version>
			<configuration>
				<excludeFilterFile>FindBugs_RulesExclude.xml</excludeFilterFile>
			</configuration>
		</plugin>
	</plugins>
</reporting>

When I specify the goal : 'clean site', I don't see the findbugs report generated and when I specify the goal : 'clean install site', I am getting findbugs report. I've read in forums that the later versions of findbugs plugin doesn't automatically trigger compile and so the project has to be compiled prior to running site. Any other alternative approach do you think?

Thanks.

**Comment by gleclaire** [comment]
The plugin should be built with Java 7 which is a Findbugs requirements itself
