### ISSUE TITLE
Find out source folder for SourceLine

### ISSUE THREAD

**Issue by JWGmeligMeyling** [gleclaire/findbugs-maven-plugin#21]
I am running FindBugs using the maven plugin in both the source and the test source folders. Now the plugin generates XML in the format:
```xml
<SourceLine role='SOURCE_LINE_DEREF' endBytecode='5' classname='nl.tudelft.jpacman.board.DirectionTest' start='47' end='47' sourcepath='nl/tudelft/jpacman/board/DirectionTest.java' sourcefile='DirectionTest.java' startBytecode='5' primary='true'>
```
For this source line, I want to know if it's from `src/main/java` or `src/test/java`. I can't find this information in the XML. Is there something I'm missing?

**Comment by slawekjaranowski** [comment]
I have similar issue. Some time ago I did proposition for resolve it but wasn't accepted.
You can look into: #1

**Comment by JWGmeligMeyling** [comment]
ah I see. Wish that one would be merged...

**Comment by gleclaire** [comment]
This is from FindBugs itself which the plugin is just a wrapper around. I think I have a potential resolution for when I implement the site target on the plugin but it will not update the xml file Findbugs produces.

I am looking into a couple change that I may be able to submit to the Findbugs main module which is a better change for this.

**Comment by JWGmeligMeyling** [comment]
Ok! :smile:
