### ISSUE TITLE
Please add bug short name in build output

### ISSUE THREAD

**Issue by athkalia** [gleclaire/findbugs-maven-plugin#27]
Hello,

it would be extremely useful for me if you could add the name of the findbugs exception in the maven console output along with it's description, so that I can instantly know what to add in my     @SuppressFBWarnings annotation. At the moment you are only outputing the description but not the short name.

Cheers,
Sakis

**Comment by athkalia** [comment]
Is this already implemented or a duplicate that I failed to spot ?

**Comment by gleclaire** [comment]
Duplicate #26
