### ISSUE TITLE
Invalid byte ... of ...-byte UTF-8 sequence.

### ISSUE THREAD

**Issue by xpyrus** [gleclaire/findbugs-maven-plugin#40]
If you have a class with german umlauts in its name, like "Testör", it will be written in the findbugsXml.xml as it is, meaning with characters > 7F (hex) - so the file will be encoded in ANSI.
But it is expected to be UTF-8, so the parsing of the file fails.

Tested with 3.0.4-Snapshot version of the maven plugin.

**Comment by gleclaire** [comment]
yes this is part of Findbugs itself.  It only does UTF-8 output

    /**
     * Write the BugCollection to given output stream as XML using a UTF8 encoding.
     * The output stream
     * will be closed, even if an exception is thrown.
     *
     * @param out
     *            the OutputStream to write to
     */
