### ISSUE TITLE
<plugins> are not added to the findbugs:gui classpath

### ISSUE THREAD

**Issue by talios** [gleclaire/findbugs-maven-plugin#42]
When adding custom findbugs plugins via `<plugins>` they seem to be copied to the `target/` directory when calling `findbugs:findbugs`, but not included in the configuration file for loading when calling `findbugs:gui` or simply calling `findbugs:check`.

It would be good to support the `<plugins>` section on both `findbugs:check` and `findbugs:gui`.

Am I missing any setting? From the javadoc, it would appear that only `findbugs:findbugs` supports `<plugins>`?

**Comment by gleclaire** [comment]
That is true.

A fix has been submitted as a pull request.  It does have a few breaking bugs that need to be worked through.




Garvin LeClaire

**Comment by talios** [comment]
And I see it right there as #37 and #38 - I should have looked closer before raising the ticket. Feel free to close this issue and I'll watch the originals.
