### ISSUE TITLE
Add html report generation

### ISSUE THREAD

**Issue by Enigo** [gleclaire/findbugs-maven-plugin#44]
The issue (and possible workarounds) I faced with is explained [here](http://stackoverflow.com/questions/38632682/maven-execute-a-goal-on-build-fail-findbugs).
Briefly the problem is if FindBugs plugin is configured with `<failOnError>true</failOnError>` property there is no easy solution to generate html reports as explained in this [answer](http://stackoverflow.com/a/10365954/5151575) 'cos html transformation task executed after FindBugs `check` goal
Xml reports as they are right now are barely readable.

**Comment by gleclaire** [comment]
if you wish to see you error there is the gui which can be run by the following:

mvn findbugs:gui

It will pick up the results from the last findbugs run.

**Comment by Enigo** [comment]
Well, this is a solution when you don't need to send the bug reports to someone who does not have Maven  installed. Or send reports via mail among others. 
Unfortunately, gui is not the option for me.
