### ISSUE TITLE
failOnError is not respected

### ISSUE THREAD

**Issue by jgangemi** [gleclaire/findbugs-maven-plugin#50]
i have `failOnError` set to `false` but my build continues to fail.

looking at the mojo source, i found this:

https://github.com/gleclaire/findbugs-maven-plugin/blob/master/src/main/groovy/org/codehaus/mojo/findbugs/FindBugsMojo.groovy#L1049

which seems to indicate `failOnError` is always set to `true`

**Comment by gleclaire** [comment]
the unit tests pass.
If you can provide a use case sample we investigate further
