### ISSUE TITLE
Release 3.0.5

### ISSUE THREAD

**Issue by vorburger** [gleclaire/findbugs-maven-plugin#52]
@gleclaire would you consider doing a 3.0.5 release?

I'm interested in it to be able to get https://github.com/gleclaire/findbugs-maven-plugin/pull/47 now...

**Comment by PascalSchumacher** [comment]
And it would be very nice if https://github.com/gleclaire/findbugs-maven-plugin/pull/53 the fix for https://github.com/gleclaire/findbugs-maven-plugin/issues/51 was included, so that the plugin works on java 9.

**Comment by hazendaz** [comment]
@gleclaire I think version 3.0.5 should be released after any issues are looked at and addressed that can be.  That will certainly help the baseline of spotbugs maven plugin.

@vorburger Please take a look at spotbugs-maven-plugin.  It has everything the master does here and is available for immediate usage.  In fact, Version 3.1.0-RC4 was just released today and will show on central index in a few hours.

**Comment by hazendaz** [comment]
@PascalSchumacher Please take a look at spotbugs-maven-plugin. It has everything the master does here and is available for immediate usage. In fact, Version 3.1.0-RC4 was just released today and will show on central index in a few hours.

**Comment by PascalSchumacher** [comment]
3.0.5 was release a few days ago and is in maven central: https://search.maven.org/#artifactdetails%7Corg.codehaus.mojo%7Cfindbugs-maven-plugin%7C3.0.5%7Cmaven-plugin

This can be closed.

**Comment by vorburger** [comment]
@hazendaz thanks for having originally pointed me to spotbugs-maven-plugin here (we're adopting it now in https://git.opendaylight.org/gerrit/#/c/64887 ...)
