### ISSUE TITLE
Most integration tests fail out-of-the-box (mvn -Prun-its clean install)

### ISSUE THREAD

**Issue by sewe** [gleclaire/findbugs-maven-plugin#58]
While developing a fix for #55, I wanted to executed the integration tests, as advertised in the `README.md`:

    mvn -Prun-its clean install

Unfortunately, most integration tests fail for me on the (unmodified) `master` branch:

    [INFO] --- maven-invoker-plugin:1.5:run (integration-test) @ findbugs-maven-plugin ---
    [INFO] Building: basic-1/pom.xml
    [INFO] ..SUCCESS (26.3 s)
    [INFO] Building: check/pom.xml
    [INFO] ..FAILED (6.2 s)
    [INFO]   The post-build script did not succeed. Expression: findbugXdoc.exists()
    …
    [INFO] -------------------------------------------------
    [INFO] Build Summary:
    [INFO]   Passed: 8, Failed: 37, Errors: 0, Skipped: 0
    [INFO] -------------------------------------------------

IMHO, this should work out-of-the-box.

**Comment by gleclaire** [comment]
This was fixed in the 3.0.5 release
