### ISSUE TITLE
"Error processing opcode invokestatic" over Jenkins with IBM JDK 8 

### ISSUE THREAD

**Issue by ivgg-me** [gleclaire/findbugs-maven-plugin#61]
During building my Project over Jenkins using IBM JDK 8 I get following errors:

	[INFO] --- findbugs-maven-plugin:3.0.4:findbugs (default-cli) @ ... ---
	[INFO] Fork Value is true

		 [java] The following errors occurred during analysis:
		 [java]   Error processing opcode invokestatic @ 0 in java.lang.String.<clinit> : ()V
		 [java]     java.lang.NullPointerException
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.processMethodCall(OpcodeStack.java:2637)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:2103)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.sawOpcode(OpcodeStack.java:2846)
		 [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:883)
		 [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory$JumpStackComputation.visitCode(OpcodeStack.java:2832)
		 [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.computeJumpInfo(OpcodeStack.java:2876)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2806)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack$JumpInfoFactory.analyze(OpcodeStack.java:2789)
		 [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.analyzeMethod(AnalysisCache.java:369)
		 [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getMethodAnalysis(AnalysisCache.java:322)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.getJumpInfo(OpcodeStack.java:3007)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.resetForMethodEntry(OpcodeStack.java:2978)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:62)
		 [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
		 [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
		 [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
		 [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
		 [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
		 [java]   Error processing opcode invokestatic @ 14 in java.lang.String.toLowerCase : (Ljava.util.Locale;)Ljava.lang.String;
		 [java]     java.lang.NullPointerException
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.processMethodCall(OpcodeStack.java:2637)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:2103)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.afterOpcode(OpcodeStackDetector.java:79)
		 [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:885)
		 [java]       At edu.umd.cs.findbugs.detect.FieldItemSummary.visit(FieldItemSummary.java:129)
		 [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:63)
		 [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
		 [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
		 [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
		 [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
		 [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
		 [java]   Error processing opcode invokestatic @ 14 in java.lang.String.toUpperCase : (Ljava.util.Locale;)Ljava.lang.String;
		 [java]     java.lang.NullPointerException
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.processMethodCall(OpcodeStack.java:2637)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:2103)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.afterOpcode(OpcodeStackDetector.java:79)
		 [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:885)
		 [java]       At edu.umd.cs.findbugs.detect.FieldItemSummary.visit(FieldItemSummary.java:129)
		 [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:63)
		 [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
		 [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
		 [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
		 [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
		 [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
		 [java]   Error processing opcode invokestatic @ 0 in java.lang.String.<clinit> : ()V
		 [java]     java.lang.NullPointerException
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.processMethodCall(OpcodeStack.java:2637)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:2103)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.afterOpcode(OpcodeStackDetector.java:79)
		 [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:885)
		 [java]       At edu.umd.cs.findbugs.detect.FieldItemSummary.visit(FieldItemSummary.java:129)
		 [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:63)
		 [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:395)
		 [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
		 [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
		 [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
		 [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
		 [java]   Error processing opcode invokestatic @ 14 in java.lang.String.toUpperCase : (Ljava.util.Locale;)Ljava.lang.String;
		 [java]     java.lang.NullPointerException
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.processMethodCall(OpcodeStack.java:2637)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:2103)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.afterOpcode(OpcodeStackDetector.java:79)
		 [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:885)
		 [java]       At edu.umd.cs.findbugs.detect.FunctionsThatMightBeMistakenForProcedures.visit(FunctionsThatMightBeMistakenForProcedures.java:155)
		 [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:63)
		 [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:386)
		 [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
		 [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
		 [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
		 [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
		 [java]   Error processing opcode invokestatic @ 14 in java.lang.String.toLowerCase : (Ljava.util.Locale;)Ljava.lang.String;
		 [java]     java.lang.NullPointerException
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.processMethodCall(OpcodeStack.java:2637)
		 [java]       At edu.umd.cs.findbugs.OpcodeStack.sawOpcode(OpcodeStack.java:2103)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.afterOpcode(OpcodeStackDetector.java:79)
		 [java]       At edu.umd.cs.findbugs.visitclass.DismantleBytecode.visit(DismantleBytecode.java:885)
		 [java]       At edu.umd.cs.findbugs.detect.FunctionsThatMightBeMistakenForProcedures.visit(FunctionsThatMightBeMistakenForProcedures.java:155)
		 [java]       At edu.umd.cs.findbugs.visitclass.BetterVisitor.visitCode(BetterVisitor.java:218)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitCode(PreorderVisitor.java:235)
		 [java]       At edu.umd.cs.findbugs.bcel.OpcodeStackDetector.visitCode(OpcodeStackDetector.java:63)
		 [java]       At org.apache.bcel.classfile.Code.accept(Code.java:135)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.doVisitMethod(PreorderVisitor.java:307)
		 [java]       At edu.umd.cs.findbugs.visitclass.PreorderVisitor.visitJavaClass(PreorderVisitor.java:386)
		 [java]       At org.apache.bcel.classfile.JavaClass.accept(JavaClass.java:215)
		 [java]       At edu.umd.cs.findbugs.BytecodeScanningDetector.visitClassContext(BytecodeScanningDetector.java:38)
		 [java]       At edu.umd.cs.findbugs.DetectorToDetector2Adapter.visitClass(DetectorToDetector2Adapter.java:76)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1089)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:283)
		 [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
		 [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
		 [java] Warnings generated: 5
	[INFO] Done FindBugs Analysis....
	[FINDBUGS] Searching for all files in ... that match the pattern findbugsXml.xml
	[FINDBUGS] Parsing 1 file in ...
	[FINDBUGS] Successfully parsed file /.../findbugsXml.xml of module ... with 5 unique warnings and 0 duplicates.
	[FINDBUGS] Computing warning deltas based on reference build #301

My Jenkins is installed on a Linux and I'm using IBM JDK 8 with following version information:

	java version "1.8.0"
	Java(TM) SE Runtime Environment (build pxa6480-20150129_02)
	IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20150116_231420 (JIT enabled, AOT enabled)
	J9VM - R28_Java8_GA_20150116_2030_B231420
	JIT  - tr.r14.java_20150109_82886.02
	GC   - R28_Java8_GA_20150116_2030_B231420_CMPRSS
	J9CL - 20150116_231420)
	JCL - 20150123_01 based on Oracle jdk8u31-b12

**Comment by gleclaire** [comment]
The currently support JDK are openjdk 7 & 8 as well as oracle 7 & 8.
If you submit a pull request for IBM sdk 8 we can add  that support.
