### ISSUE TITLE
Update FindBugs to 3.0.2

### ISSUE THREAD

**Issue by RobertPaasche** [gleclaire/findbugs-maven-plugin#65]
We currently the following findbugs error wich was fixed in 3.0.2 from march:
https://sourceforge.net/p/findbugs/bugs/1374/

We override the Version in our pom.xml but it would be nice to have the current version used by default.

**Comment by RobertPaasche** [comment]
Hmm ok isn't released yet ...

**Comment by hazendaz** [comment]
@RobertPaasche Not only is that not released, the community has forked from findbugs to spotbugs.  You might want to give spotbugs a try to see if it resolves the issue you are tracking.

See [spotbugs]https://github.com/spotbugs

At the moment I own a branch off this repo for releasing maven support for spotbugs.  We are working to bring that to spotbugs organization as well as see what we should do about the situation here.  Mainly do we continue to have separate findbugs maven plugin just in case along with a cut on spotbugs.  For now that works but certainly more concerned if your issues is addressed in that revision.  Please let me know.
