### ISSUE TITLE
Spotbugs Project

### ISSUE THREAD

**Issue by hazendaz** [gleclaire/findbugs-maven-plugin#67]
@gleclaire 

[Spotbugs](https://github.com/spotbugs) is a community replacement of findbugs.  Information can be followed over on spotbugs.

A couple of months ago, there was some talk about what to do with findbugs maven plugin since spotbugs is drop in place replacement.  Since I already had a fork, the decision was made to use a branch there and get that released.  Everything is in RC status currently with spotbugs.  In order to be as compliant or close to findbugs maven plugin as possible I raised a few pull requests to apply additional work I was doing.  Two versions have been released for spotbugs at this point with second one ironing out some issues the updates I had been working for newer maven presented to findbugs plugins (in new PR today against this repo).  Now quite a number of projects are using spotbugs maven plugin or spotbugs variation (checkstyle, fbcontrib, findsecbugs).  The first official release of spotbugs-maven-plugin occurred on 6/29.  Already there are 200 downloads shown on central statistics which I suspect is greatly going to grow as word gets out.

Yesterday all my current pull requests were merged into findbugs maven plugin.  I have since rebased and sent another pull request while releasing another spotbugs maven plugin picking up other changes in recent week to this project.

Yesterday I was invited into the spotbugs project and asked to donate the code to them or keep versions sync'd.  So my thought initially was that I wasn't getting any real traction here and probably would completely flip the repo over to them but still keep it showing it's original roots forked from here.  At that point the master there would become all about spotbugs.  Now that my PRs are merged, I still think that is appropriate but before doing anything wanted to get some feedback if it makes sense to have two separate repos for the needs here where any issues on legacy at least for some time are addressed here at findbugs maven plugin then consumed over on spotbugs maven plugin, or if this project should just entirely flip over to spotbugs.

I did release spotbugs-maven-plugin today aligning with their version scheme.

Thoughts?

**Comment by gleclaire** [comment]
having them plugin as part of the big project is a good idea.

**Comment by iloveeclipse** [comment]
@gleclaire : you are welcome if you want to join SpotBugs project. Just drop a mail to me.

**Comment by iloveeclipse** [comment]
@gleclaire : may I ask you for help with https://github.com/spotbugs/spotbugs/issues/8? See last comment from @hazendaz. It would be great to have you on board in SpotBugs project. We are preparing first public SpotBugs release, and the maven part relly need some polishing.

**Comment by hazendaz** [comment]
@gleclaire My intentions at the moment are to provide continued support for the original findbugs maven plugin thus trying to get fixes and such up there.  It would be awesome if I could get committer access on this repo so I can speed that up a bit when I need to.  On the spotbugs project, there is intended to mostly address spotbugs new features.  By doing this I have the spotbugs-maven-plugin tied to the master from findbugs-maven-plugin and separate spotbugs branch for spotbugs needs.  At the moment I'm rebasing over there on spotbugs branch (particuarly becuase I hate dummy merges).  Hope that helps to understand my motivations at the moment.

**Comment by gleclaire** [comment]
I think we can close this.

**Comment by hazendaz** [comment]
All good.  Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
