### ISSUE TITLE
Plugin does not work with Java 9

### ISSUE THREAD

**Issue by aaron-haskins** [gleclaire/findbugs-maven-plugin#73]
Trying to run the plugin with [Java 9](http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html) fails:

	[INFO] 
	[INFO] >>> findbugs-maven-plugin:3.0.5:check (default) > :findbugs @ Java >>>
	[INFO] 
	[INFO] --- findbugs-maven-plugin:3.0.5:findbugs (findbugs) @ Java ---
	[INFO] Fork Value is true
	     [java] WARNING: An illegal reflective access operation has occurred
	     [java] WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:/Users/james/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
	     [java] WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
	     [java] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
	     [java] WARNING: All illegal access operations will be denied in a future release
	     [java] Warning: Unknown version of Java
	     [java] edu.umd.cs.findbugs.JavaVersionException: Could not parse Java version string: 9
	     [java] 	at edu.umd.cs.findbugs.JavaVersion.<init>(JavaVersion.java:68)
	     [java] 	at edu.umd.cs.findbugs.JavaVersion.<clinit>(JavaVersion.java:44)
	     [java] 	at edu.umd.cs.findbugs.DetectorFactory.isEnabledForCurrentJRE(DetectorFactory.java:248)
	     [java] 	at edu.umd.cs.findbugs.FindBugs.isDetectorEnabled(FindBugs.java:256)
	     [java] 	at edu.umd.cs.findbugs.FindBugs2$3.choose(FindBugs2.java:906)
	     [java] 	at edu.umd.cs.findbugs.plan.ExecutionPlan.build(ExecutionPlan.java:168)
	     [java] 	at edu.umd.cs.findbugs.FindBugs2.createExecutionPlan(FindBugs2.java:935)
	     [java] 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:241)
	     [java] 	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
	     [java] 	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)

**Comment by gleclaire** [comment]
This is a Findbugs issue.  Have a look at Spotbugs https://spotbugs.github.io/

**Comment by hazendaz** [comment]
@aaron-haskins Here is the maven coordinates for spotbugs.

```
<dependency>
    <groupId>com.github.spotbugs</groupId>
    <artifactId>spotbugs-maven-plugin</artifactId>
    <version>3.1.0-RC6</version>
</dependency>
```
