### ISSUE TITLE
Not able to run integrations tests on clean checkout

### ISSUE THREAD

**Issue by lqc** [gleclaire/findbugs-maven-plugin#83]
After running:

`mvn -DtestSrc=remote -Prun-its clean install`

I get:

```
Building: prime/pom.xml
          prime/pom.xml .................................... FAILED (12.3 s)
  The build exited with code 1. See [...]/findbugs-maven-plugin/target/it/prime/build.log for details.
```

And inside is this message

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.922 s
[INFO] Finished at: 2017-10-13T17:47:24+02:00
[INFO] Final Memory: 15M/246M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project prime: Could not resolve dependencies for project findbugs-maven-plugin.it:prime:jar:testing: Could not find artifact org.codehaus.mojo:findbugs-maven-plugin:jar:3.0.6-SNAPSHOT  in local.central (...) -> [Help 1]
```

I'm not sure why "it-tools" are run in a separate execution in "pre-integration-test" phase, so I'm not sure how to fix this.

Edit: pasted the log from spotbugs by accident which has the same problem.

**Comment by hazendaz** [comment]
@gleclaire The execution phase is bad.  Removing it fixes this issue.  I'm not entirely sure what the thought was there.

With phase removed this occurs

integraton-test-setup
prepare-integration-test-remote-findbugs-src
prepare-integration-test  ***
integration-test-run

*** would otherwise try to run first which I think is in the wrong spot.  I can see wanting that before downloading the findbugs source.  I"m trying to figure that out assuming that is the need.

**Comment by hazendaz** [comment]
I got this working, PR coming shortly.

New order...

integration-test-setup
prepare-integration-test
prepare-integration-test-remote-findbugs-src
integration-test-run

**Comment by lqc** [comment]
Right, but why not just have a single execution with

```
 <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-invoker-plugin</artifactId>
            <version>${invokerPluginVersion}</version>
            <executions>
              <execution>
                <id>integration-tests</id>
                <goals>
                  <goal>install</goal>
                  <goal>run</goal>
                </goals>
               ... all the other config
</plugin>
```

as per maven-invoker-plugin docs (btw, invoker plugin already does the install in {{pre-*}})? Is there something special about the two tests that are in `it-tools`  that need a separate execution in a prepare phase?

**Comment by gleclaire** [comment]
The build-tools test creates the include/exclude resources used for tests.  The prime project has the dependencies that the other tests require.  By doing this on a single thread we will not have any file contention for the shared local repository with the later parallel tests.
