### ISSUE TITLE
findbugs maven plugin not support for Java 1.8

### ISSUE THREAD

**Issue by shootingsyh** [gleclaire/findbugs-maven-plugin#9]
findbugs maven plugin will crash with exception as below when build using java 1.8. And with findbugs 3.0.0 release, it actually supports Java 1.8. Should the maven plugin match the progress?:
    [java] The following errors occurred during analysis:
     [java]   Unable to get XClass for java/lang/StringBuilder
     [java]     java.lang.ArrayIndexOutOfBoundsException: 5747
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/lang/String
     [java]     java.lang.ArrayIndexOutOfBoundsException: 5747
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/lang/Class
     [java]     java.lang.ArrayIndexOutOfBoundsException: 207
     [java]       At org.objectweb.asm.ClassReader.a(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.readUTF8(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 40705
     [java] 	at org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java] 	at edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java] 	at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java] 	at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java] 	at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java] 	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java] 	at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java] 	at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java] 	at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.getXMethod(TypeQualifierNullnessAnnotationDatabase.java:363)
     [java] 	at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.addMethodParameterAnnotation(TypeQualifierNullnessAnnotationDatabase.java:425)
     [java] 	at edu.umd.cs.findbugs.ba.DefaultNullnessAnnotations.addDefaultNullnessAnnotations(DefaultNullnessAnnotations.java:69)
     [java] 	at edu.umd.cs.findbugs.ba.npe.TypeQualifierNullnessAnnotationDatabase.loadAuxiliaryAnnotations(TypeQualifierNullnessAnnotationDatabase.java:460)
     [java] 	at edu.umd.cs.findbugs.ba.AnalysisContext.updateDatabases(AnalysisContext.java:962)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.analyzeApplication(FindBugs2.java:1154)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:282)
     [java] 	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java] 	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)

**Comment by gleclaire** [comment]
The plugin should be built with Java 7 which is a Findbugs requirements itself
